# =======================================================
# GENERAL / PATH FIXES
# =======================================================
baseURL = "https://hacvavang.github.io/fcj-workshop/"
relativeURLs = false
canonifyURLs = false

defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

# Fixes language prefix handling for site asset links across /vi/ pages
disablePathToLower = false

# Enables automatic language detection based on browser settings
defaultContentLanguageInAutoDir = false

# Change the default theme to be used when building the site with Hugo
theme = "hugo-theme-learn"

# For search functionality
[outputs]
  home = ["HTML", "RSS", "JSON"]

# =======================================================
# THEME PARAMS (hugo-theme-learn specific)
# =======================================================
[params]
  themeVariant = "workshop"
  editURL = ""
  description = "Internship Report"
  author = "thienlh@thienlu.com"
  showVisitedLinks = true
  disableBreadcrumb = false
  disableNextPrev = false
  
  # Adds language selector in sidebar
  disableLanguageSwitchingButton = false
  
  # Cleans up sidebar UI
  disableLandingPageButton = false
  disableSearch = false

# =======================================================
# MULTILINGUAL SETTINGS
# =======================================================
[languages]
  [languages.en]
    title = "Internship Report"
    weight = 1
    label = "English"
    languageName = "English"

    [[languages.en.menu.shortcuts]]
      name = "<i class='fab fa-aws'></i> AWS Study Group - Blog"
      identifier = "AWS Study Group"
      url = "https://awsstudygroup.com"
      weight = 20

    [[languages.en.menu.shortcuts]]
      name = "<i class='fab fa-facebook'></i> AWS Study Group - FB Group"
      identifier = "AWS Study Group FB"
      url = "https://www.facebook.com/groups/awsstudygroupfcj"
      weight = 20

  [languages.vi]
    title = "Báo cáo thực tập"
    weight = 2
    label = "Tiếng Việt"
    languageName = "Tiếng Việt"

    [[languages.vi.menu.shortcuts]]
      name = "<i class='fab fa-aws'></i> AWS Study Group - Blog"
      identifier = "AWS Study Group"
      url = "http://awsstudygroup.com"
      weight = 20

    [[languages.vi.menu.shortcuts]]
      name = "<i class='fab fa-facebook'></i> AWS Study Group - Nhóm FB"
      identifier = "AWS Study Group FB"
      url = "https://www.facebook.com/groups/awsstudygroupfcj"
      weight = 20

# =======================================================
# MARKDOWN RENDERER
# =======================================================
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true